services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: tqc-app
        working_dir: /var/www
        ports:
            - 80:80
        volumes:
            - .:/var/www
            - ./build/default.conf:/etc/nginx/conf.d/default.conf
            - ./build/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf
        networks:
            - tqc-network
        depends_on:
            - db

    db:
        image: postgres:13
        container_name: tqc-db
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: talks-quality-checker
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - tqc-network

volumes:
    db_data:

networks:
    tqc-network:
        driver: bridge
